name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIR: .
      FILE: cv-pt
      FILE-ENG: cv-en
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: cv
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE }}
          working_directory: ${{ env.DIR }}
      - name: cv-en
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE-ENG }}
          working_directory: ${{ env.DIR }}
      - name: move pt cv
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/
      - name: move en cv
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE-ENG }}.pdf ./github_artifacts/
      - name: Upload pdfs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: ./github_artifacts
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
          enable_jekyll: true